### ISSUE TITLE
Thanks and are you planning to release evaluation code?

### ISSUE THREAD

**Issue by tholmb** [sooyekim/MaskDepth#2]
Wonderful work! I know that you might be busy related to graduation but I would like to know that do you have any plans to release evaluation code and the model? It would be a pleasure to test your method with own depth maps and masks!

**Comment by javierztl** [comment]
same question

**Comment by sooyekim** [comment]
@tholmb @javierztl Thanks for your interest in our work! The inference code has been released here: https://github.com/adobe-research/layered-depth-refinement
